money-trees/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'home/index'
  get 'home/contact'
  get 'home/about'
  get 'home/help'

  get '/help', to: 'home#help'
  get '/about', to: 'home#about'
  get '/contact', to: 'home#contact'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  get '/user/dashboard', to: 'users#show', :as => :user_dashboard
  get '/user/grows', to: 'users#grows', :as => :user_grows
  get '/user/rooms', to: 'users#rooms', :as => :user_rooms
  get '/user/plants', to: 'users#plants', :as => :user_plants

  resources :rooms
  resources :strains
  resources :plants
  resources :grows
  resources :users

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

money-trees/app/models/room.rb
class Room < ApplicationRecord
  mount_uploader :picture, ::PictureUploader
  belongs_to :grow
  has_many :plants
end

money-trees/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :correct_user, only: [:index, :show, :edit, :update]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
      @grow = Grow.find(@room.grow_id)
      @user = @grow.user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :grow_id, :picture)
    end
end

money-trees/app/helpers/rooms_helper.rb
module RoomsHelper
end

money-trees/app/views/rooms/_form.html.erb
<%= form_for(room) do |f| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :grow_id %>
    <%= f.number_field :grow_id %>
  </div>

  <span class="picture">
    <%= f.file_field :picture %>
  </span>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

money-trees/app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

money-trees/app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Grow</th>
      <th>Plants</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name.titleize %></td>
        <td><%= room.grow_id %></td>
        <td><%= room.plants.count %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

money-trees/app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

money-trees/app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @room.name %></h1>

<p>
  <strong>Grow:</strong>
  <%= @room.grow_id %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

<h2>Plants</h2>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Strain</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @room.plants.each do |plant| %>
      <tr>
        <td><%= plant.name.titleize %></td>
        <td><%= plant.strain %></td>
        <td><%= link_to 'Show', plant %></td>
        <td><%= link_to 'Edit', edit_plant_path(plant) %></td>
        <td><%= link_to 'Destroy', plant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>