money-trees/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'home/index'
  get 'home/contact'
  get 'home/about'
  get 'home/help'

  get '/help', to: 'home#help'
  get '/about', to: 'home#about'
  get '/contact', to: 'home#contact'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  get '/user/dashboard', to: 'users#show', :as => :user_dashboard
  get '/user/grows', to: 'users#grows', :as => :user_grows
  get '/user/rooms', to: 'users#rooms', :as => :user_rooms
  get '/user/plants', to: 'users#plants', :as => :user_plants

  resources :rooms
  resources :strains
  resources :plants
  resources :grows
  resources :users

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

money-trees/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    &copy; <%= Date.today.year %> Money Trees mothafuckin grow management system
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

money-trees/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Money Trees", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Dashboard", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user.id) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

money-trees/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

money-trees/app/views/layouts/_user-nav.html.erb
<ul class="list-group user-nav">
  <%= link_to user_dashboard_path do %>
      <li class="active list-group-item">Dashboard</li>
  <% end %>
  <%= link_to user_grows_path do %>
      <li class="list-group-item">
        <span class="badge"><%= @user.grows.count %></span>
        Grows
      </li>
  <% end %>
  <%= link_to user_rooms_path do %>
      <li class="list-group-item">
        <span class="badge"><%= @user.rooms.count %></span>
        Rooms
      </li>
  <% end %>
  <%= link_to user_plants_path do %>
      <li class="list-group-item">
        <span class="badge"><%= @user.plants.count %></span>
        Plants
      </li>
  <% end %>
  <%= link_to user_dashboard_path do %>
      <li class="list-group-item">
        <span class="badge"><%= @user.strains.count %></span>
        Strains
      </li>
  <% end %>
</ul>

money-trees/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>