money-trees/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'home/index'
  get 'home/contact'
  get 'home/about'
  get 'home/help'

  get '/help', to: 'home#help'
  get '/about', to: 'home#about'
  get '/contact', to: 'home#contact'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  get '/user/dashboard', to: 'users#show', :as => :user_dashboard
  get '/user/grows', to: 'users#grows', :as => :user_grows
  get '/user/rooms', to: 'users#rooms', :as => :user_rooms
  get '/user/plants', to: 'users#plants', :as => :user_plants

  resources :rooms
  resources :strains
  resources :plants
  resources :grows
  resources :users

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

money-trees/app/models/grow.rb
class Grow < ApplicationRecord
  mount_uploader :picture, ::PictureUploader
  belongs_to :user
  has_many :plants
  has_many :rooms
  validates :user_id, presence: true

  def strains
    Strain.where(id: plants.pluck(:strain_id))
  end
end

money-trees/app/controllers/grows_controller.rb
class GrowsController < ApplicationController
  before_action :set_grow, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :correct_user, only: [:index, :show, :edit, :update]

  # GET /grows
  # GET /grows.json
  def index
    @grows = Grow.all
  end

  # GET /grows/1
  # GET /grows/1.json
  def show
  end

  # GET /grows/new
  def new
    @grow = Grow.new
  end

  # GET /grows/1/edit
  def edit
  end

  # POST /grows
  # POST /grows.json
  def create
    user = current_user
    @grow = user.grows.build(grow_params)

    respond_to do |format|
      if @grow.save
        format.html { redirect_to @grow, notice: 'Grow was successfully created.' }
        format.json { render :show, status: :created, location: @grow }
      else
        format.html { render :new }
        format.json { render json: @grow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grows/1
  # PATCH/PUT /grows/1.json
  def update
    respond_to do |format|
      if @grow.update(grow_params)
        format.html { redirect_to @grow, notice: 'Grow was successfully updated.' }
        format.json { render :show, status: :ok, location: @grow }
      else
        format.html { render :edit }
        format.json { render json: @grow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grows/1
  # DELETE /grows/1.json
  def destroy
    @grow.destroy
    respond_to do |format|
      format.html { redirect_to grows_url, notice: 'Grow was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grow
      @grow = Grow.find(params[:id])
      @user = @grow.user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grow_params
      params.require(:grow).permit(:name, :user_id, :picture)
    end
end

money-trees/app/helpers/grows_helper.rb
module GrowsHelper
end

money-trees/app/views/grows/_form.html.erb
<%= form_for(grow, html: { multipart: true }) do |f| %>
  <% if grow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grow.errors.count, "error") %> prohibited this grow from being saved:</h2>

      <ul>
      <% grow.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <span class="picture">
    <%= f.file_field :picture %>
  </span>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

money-trees/app/views/grows/edit.html.erb
<h1>Editing Grow</h1>

<%= render 'form', grow: @grow %>

<%= link_to 'Show', @grow %> |
<%= link_to 'Back', grows_path %>

money-trees/app/views/grows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Grows</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grows.each do |grow| %>
      <tr>
        <td><%= grow.name %></td>
        <td><%= grow.user_id %></td>
        <td><%= link_to 'Show', grow %></td>
        <td><%= link_to 'Edit', edit_grow_path(grow) %></td>
        <td><%= link_to 'Destroy', grow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grow', new_grow_path %>

money-trees/app/views/grows/new.html.erb
<h1>New Grow</h1>

<%= render 'form', grow: @grow %>

<%= link_to 'Back', grows_path %>

money-trees/app/views/grows/show.html.erb
<div class="row">
  <p id="notice"><%= notice %></p>
</div>

<div class="center jumbotron" style="background-image: url('<%= @grow.picture if @grow.picture? %>')">
  <h1><%= @grow.name.titleize %></h1>
</div>

<div class="row">
  <div class="col-md-9">
    <h3>Welcome to <%= @grow.name.titleize %></h3>
  </div>
  <div class="col-md-3">
    <%= link_to 'Edit', edit_grow_path(@grow) %>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-md-3">
    <h4>Rooms</h4>
    <div class="chart" data-percent="<%= @grow.rooms.count %>" data-scale-color="#ffb400"><%= @grow.rooms.count %></div>
  </div>
  <div class="col-md-3">
    <h4>Plants</h4>
    <div class="chart" data-percent="<%= @grow.plants.count %>" data-scale-color="#ffb400"><%= @grow.plants.count %></div>
  </div>
  <div class="col-md-3">
    <h4>Strains</h4>
    <div class="chart" data-percent="<%= @grow.strains.count %>" data-scale-color="#ffb400"><%= @grow.strains.count %></div>
  </div>
  <div class="col-md-3">
    <h4>Strains</h4>
    <div class="chart" data-percent="<%= @grow.strains.count %>" data-scale-color="#ffb400"><%= @grow.strains.count %></div>
  </div>
</div>
<hr>
<div class="row">
  <h2>Rooms</h2>


  <ul class="col-md-12 grows">
    <% @grow.rooms.each do |room| %>
        <%= link_to room do %>
            <li class="col-md-12 room" style="background-image: url('<%= room.picture.url if room.picture? %>')">
              <p>Name: <%=  room.name.titleize %></p>
              <p>Plants: <%= room.plants.count %></p>
            </li>
        <% end %>
    <% end %>
  </ul>

</div>

<script>
    $(function() {
        $('.chart').easyPieChart({
            lineWidth:8,
            scaleLength:0
        });
    });
</script>